Finalne zadanie z utworzonym repozytorium
pplutap/jdp-2310-01 pull request #15
Opened 2023-10-04 21:43 UTC by programer33333

2023-10-04 21:54 UTC, programer33333 commented
powinienem inaczej nazwać commita "JDP231001-14"

2023-10-05 05:02 UTC, pplutap commented
Nazwę commita możesz zmienić za pomocą polecenia `git commit --amend`

2023-10-05 05:03 UTC, pplutap requested changes

2023-10-05 05:03 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +            cascade = CascadeType.ALL,
Usuwając koszyk, zostaną usunięte wszystkie produkty - nie tylko z koszyka, zostaną usunięte z bazy danych

2023-10-05 17:38 UTC, programer33333 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +            cascade = CascadeType.ALL,
czy wystarczy że usunę wiersz 32?

2023-10-08 06:41 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +            cascade = CascadeType.ALL,
Tak, jednak może pojawić się problem z zapisem danych

2023-10-10 17:06 UTC, pplutap approved these changes

2023-10-10 18:11 UTC, Palomza approved these changes

2023-10-11 08:41 UTC, merged