Jdp231001 16
pplutap/jdp-2310-01 pull request #18
Opened 2023-10-10 08:44 UTC by DamianNu

2023-10-10 16:45 UTC, Palomza approved these changes

2023-10-10 16:48 UTC, pplutap requested changes

2023-10-10 16:48 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private String name;
W jakim celu potrzebne jest `name`?

2023-10-10 17:12 UTC, pplutap requested changes

2023-10-10 17:12 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    public Order order;
User może mieć wiele obiektów typu Order, czy relacja jest na pewno potrzebna?

2023-10-11 07:41 UTC, DamianNu commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    public Order order;
Racja relacja nie jest potrzebna

2023-10-11 07:44 UTC, DamianNu commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private String name;
Sam nie wiem w jakim celu dodałem 'name'.

2023-10-13 06:52 UTC, pplutap commented
Zrób proszę rebase brancha

2023-10-13 17:34 UTC, DamianNu commented
Rebase wykonany

2023-10-14 20:25 UTC, pplutap commented
@DamianNu github cały czas pokazuje konflikty

2023-10-15 08:22 UTC, closed without merging